import type { SchemaGraphKernel } from '../core/create-schema-graph-kernel.js';
import type { Property } from '@atomos-web/structura-core';

const mapTsType = (dataType: string): string => {
  switch (dataType) {
    case 'number':
    case 'integer':
    case 'float':  return 'number';
    case 'boolean': return 'boolean';
    case 'date':    return 'Date';
    default:        return 'string';
  }
};

export const createTypescriptAdapter = (kernel: SchemaGraphKernel) => {
  return Object.freeze({
    generateInterfaces: (): string => {
      const { entities, links } = kernel.getSnapshot();
      const lines: string[] = [
        '// Auto-generated by atomos-structura',
        '',
      ];

      Object.values(entities).forEach(entity => {
        lines.push(`export interface ${entity.name} {`);

        entity.properties.forEach((prop: Property) => {
          const tsType = mapTsType(prop.dataType);
          const optional = prop.validation?.required ? '' : '?';
          lines.push(`  ${prop.key}${optional}: ${tsType};`);
        });

        // Outgoing relations
        const outgoing = Object.values(links).filter(l => l.leftEntityId === entity.id);
        outgoing.forEach(link => {
          const target = entities[link.rightEntityId];
          if (!target) return;
          const isMany = link.rightCardinality === '*' || link.rightCardinality === '1..*';
          const fieldName = target.name.charAt(0).toLowerCase() + target.name.slice(1);
          lines.push(`  ${fieldName}${isMany ? '' : '?'}: ${target.name}${isMany ? '[]' : ''};`);
        });

        lines.push('}', '');
      });

      return lines.join('\n');
    },
  });
};
